# -*- coding: utf-8 -*-
"""RL Orchestrator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G8i7zKIehGOk3WdFlinuTX49XUR8eMI0
"""

import gymnasium as gym
import numpy as np
import networkx as nx
import torch
import torch.nn as nn
from gymnasium import spaces
from sb3_contrib import MaskablePPO
from sb3_contrib.common.maskable.policies import MaskableActorCriticPolicy
from sb3_contrib.common.wrappers import ActionMasker
from stable_baselines3.common.torch_layers import BaseFeaturesExtractor
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.results_plotter import load_results, ts2xy
import matplotlib.pyplot as plt
import os

# ==========================================
# 1. CONFIGURATION
# ==========================================
SUBSTRATE_NODES = 15
SUBSTRATE_CPU_CAP = 100
SUBSTRATE_LINK_BW = 100
MAX_VNR_NODES = 4
NUM_ALTERNATIVES = 2
TRAINING_STEPS = 25000
TARGET_REQS = 200             # Fair Evaluation Target

# ==========================================
# 2. DATA GENERATOR
# ==========================================
class GraphGenerator:
    @staticmethod
    def generate_substrate(num_nodes=SUBSTRATE_NODES):
        G = nx.barabasi_albert_graph(num_nodes, 3)
        for u in G.nodes:
            G.nodes[u]['cpu'] = np.random.randint(50, SUBSTRATE_CPU_CAP)
            G.nodes[u]['max_cpu'] = G.nodes[u]['cpu']
        for u, v in G.edges:
            G.edges[u, v]['bw'] = np.random.randint(50, SUBSTRATE_LINK_BW)
            G.edges[u, v]['max_bw'] = G.edges[u, v]['bw']
        return G

    @staticmethod
    def generate_request_alternatives():
        """
        Alt 1: Compute Heavy (High CPU, Low BW)
        Alt 2: Bandwidth Heavy (Low CPU, High BW)
        """
        num_nodes = np.random.randint(3, MAX_VNR_NODES + 1)
        base = nx.path_graph(num_nodes)

        # Alt 1: Compute Heavy
        alt1 = base.copy()
        for u in alt1.nodes:
            alt1.nodes[u]['cpu'] = np.random.randint(20, 30)
        for u, v in alt1.edges:
            alt1.edges[u, v]['bw'] = np.random.randint(5, 10)

        # Alt 2: Bandwidth Heavy
        alt2 = base.copy()
        for u in alt2.nodes:
            alt2.nodes[u]['cpu'] = np.random.randint(5, 10)
        for u, v in alt2.edges:
            alt2.edges[u, v]['bw'] = np.random.randint(20, 30)

        return [alt1, alt2]

# ==========================================
# 3. ENVIRONMENT
# ==========================================
class VNEAPEnv(gym.Env):
    def __init__(self):
        super().__init__()
        self.substrate = GraphGenerator.generate_substrate()
        self.initial_substrate = self.substrate.copy()

        self.total_cpu = sum(nx.get_node_attributes(self.substrate, 'max_cpu').values())
        self.total_bw = sum(nx.get_edge_attributes(self.substrate, 'max_bw').values()) * 2

        self.observation_space = spaces.Dict({
            "substrate_cpu": spaces.Box(low=0, high=SUBSTRATE_CPU_CAP, shape=(SUBSTRATE_NODES,), dtype=np.float32),
            "request_state": spaces.Box(low=0, high=100, shape=(NUM_ALTERNATIVES, MAX_VNR_NODES), dtype=np.float32),
            "phase_indicator": spaces.Discrete(2) # 0=Selection, 1=Mapping
        })

        self.action_space = spaces.Discrete(SUBSTRATE_NODES)

        self.current_alts = []
        self.selected_alt_idx = None
        self.mapping_phase = False
        self.current_v_node_idx = 0
        self.mapped_nodes = {}
        self.active_deployments = []

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        self.substrate = GraphGenerator.generate_substrate()
        self.total_cpu = sum(nx.get_node_attributes(self.substrate, 'max_cpu').values())
        bw_caps = nx.get_edge_attributes(self.substrate, 'max_bw')
        self.total_bw = sum(bw_caps.values()) if bw_caps else 1

        self.current_alts = GraphGenerator.generate_request_alternatives()

        self.mapping_phase = False
        self.selected_alt_idx = None
        self.current_v_node_idx = 0
        self.mapped_nodes = {}
        self.active_deployments = []

        return self._get_obs(), {}

    def _get_obs(self):
        sub_cpu = np.array([self.substrate.nodes[n]['cpu'] for n in range(SUBSTRATE_NODES)], dtype=np.float32)
        req_matrix = np.zeros((NUM_ALTERNATIVES, MAX_VNR_NODES), dtype=np.float32)
        for i, alt in enumerate(self.current_alts):
            for j, node in enumerate(alt.nodes):
                if j < MAX_VNR_NODES:
                    req_matrix[i][j] = alt.nodes[node]['cpu']

        return {
            "substrate_cpu": sub_cpu,
            "request_state": req_matrix,
            "phase_indicator": 1 if self.mapping_phase else 0
        }

    def get_utilization(self):
        current_cpu = sum(nx.get_node_attributes(self.substrate, 'cpu').values())
        used_cpu = self.total_cpu - current_cpu
        current_bw = sum(nx.get_edge_attributes(self.substrate, 'bw').values())
        used_bw = self.total_bw - current_bw if self.total_bw > 0 else 0
        return (used_cpu / self.total_cpu) * 100, (used_bw / self.total_bw) * 100

    def action_masks(self):
        mask = np.zeros(SUBSTRATE_NODES, dtype=bool)
        if not self.mapping_phase:
            for i in range(len(self.current_alts)):
                mask[i] = True
        else:
            needed_cpu = self.current_alts[self.selected_alt_idx].nodes[self.current_v_node_idx]['cpu']
            for i in range(SUBSTRATE_NODES):
                if self.substrate.nodes[i]['cpu'] >= needed_cpu:
                    if i not in self.mapped_nodes.values():
                        mask[i] = True
        return mask

    def _map_links(self, graph, mapping):
        allocated_paths = []
        for u, v in graph.edges:
            p_u, p_v = mapping[u], mapping[v]
            bw_needed = graph.edges[u, v]['bw']

            try:
                path = nx.shortest_path(self.substrate, source=p_u, target=p_v, weight=None)
                for i in range(len(path) - 1):
                    s, d = path[i], path[i+1]
                    if self.substrate[s][d]['bw'] < bw_needed:
                        raise nx.NetworkXNoPath

                for i in range(len(path) - 1):
                    s, d = path[i], path[i+1]
                    self.substrate[s][d]['bw'] -= bw_needed
                    allocated_paths.append((s, d, bw_needed))

            except nx.NetworkXNoPath:
                for s, d, amt in allocated_paths:
                    self.substrate[s][d]['bw'] += amt
                return False, []
        return True, allocated_paths

    def step(self, action):
        if isinstance(action, (np.ndarray, np.generic)):
            action = int(action)

        reward = 0
        done = False
        info = {}

        # Departure Process
        if self.active_deployments and np.random.rand() < 0.15:
            dep = self.active_deployments.pop(0)
            for p_node, cpu_amt in dep['nodes']:
                self.substrate.nodes[p_node]['cpu'] = min(self.substrate.nodes[p_node]['max_cpu'],
                                                          self.substrate.nodes[p_node]['cpu'] + cpu_amt)
            for u, v, bw_amt in dep['links']:
                self.substrate[u][v]['bw'] = min(self.substrate[u][v]['max_bw'],
                                                 self.substrate[u][v]['bw'] + bw_amt)

        if not self.mapping_phase:
            self.selected_alt_idx = action
            self.mapping_phase = True
        else:
            p_node = action
            v_node = self.current_v_node_idx
            selected_graph = self.current_alts[self.selected_alt_idx]
            cpu_demand = selected_graph.nodes[v_node]['cpu']

            if self.substrate.nodes[p_node]['cpu'] < cpu_demand:
                reward = -50
                info['msg'] = "Mapping Failed (CPU)"
                self._reset_request_state()
            else:
                self.substrate.nodes[p_node]['cpu'] -= cpu_demand
                self.mapped_nodes[v_node] = (p_node, cpu_demand)
                reward = -(0.05 * cpu_demand)

                self.current_v_node_idx += 1

                if self.current_v_node_idx >= len(selected_graph.nodes):
                    simple_map = {v: p[0] for v, p in self.mapped_nodes.items()}
                    success, path_data = self._map_links(selected_graph, simple_map)

                    if success:
                        reward += 50
                        info['msg'] = "Fully Embedded"
                        self.active_deployments.append({
                            'nodes': list(self.mapped_nodes.values()),
                            'links': path_data
                        })
                    else:
                        reward = -20
                        info['msg'] = "Mapping Failed (BW)"
                        for p_node, amt in self.mapped_nodes.values():
                            self.substrate.nodes[p_node]['cpu'] += amt

                    self._reset_request_state()

        return self._get_obs(), reward, done, False, info

    def _reset_request_state(self):
        self.current_alts = GraphGenerator.generate_request_alternatives()
        self.mapping_phase = False
        self.selected_alt_idx = None
        self.current_v_node_idx = 0
        self.mapped_nodes = {}

# ==========================================
# 4. HEURISTICS
# ==========================================
class HeuristicAgent:
    def __init__(self, name): self.name = name
    def predict(self, env):
        if not env.mapping_phase: return self.select_alternative(env)
        else: return self.map_node(env)
    def map_node(self, env):
        needed = env.current_alts[env.selected_alt_idx].nodes[env.current_v_node_idx]['cpu']
        mapped_p_nodes = [val[0] if isinstance(val, tuple) else val for val in env.mapped_nodes.values()]
        for i in range(SUBSTRATE_NODES):
             if env.substrate.nodes[i]['cpu'] >= needed and i not in mapped_p_nodes:
                 return i
        return 0
    def select_alternative(self, env): raise NotImplementedError

class GreedyAgent(HeuristicAgent):
    def select_alternative(self, env):
        best_idx, min_cost = 0, float('inf')
        for i, alt in enumerate(env.current_alts):
            cost = sum(nx.get_node_attributes(alt, 'cpu').values()) + sum(nx.get_edge_attributes(alt, 'bw').values())
            if cost < min_cost:
                min_cost = cost
                best_idx = i
        return best_idx

class TantoProxyAgent(HeuristicAgent):
    """
    TANTO (Proxy): Resource-Aware Load Balancing.
    Logic: Checks network scarcity (CPU vs BW) and penalizes the heavily used resource.
    """
    def select_alternative(self, env):
        # 1. Determine Network State
        total_cpu_cap = env.total_cpu
        total_bw_cap = env.total_bw

        current_cpu_used = total_cpu_cap - sum(nx.get_node_attributes(env.substrate, 'cpu').values())
        current_bw_used = total_bw_cap - sum(nx.get_edge_attributes(env.substrate, 'bw').values())

        # Calculate global utilization (0.0 to 1.0)
        cpu_util = current_cpu_used / total_cpu_cap
        bw_util = current_bw_used / (total_bw_cap if total_bw_cap > 0 else 1)

        best_idx = 0
        best_score = float('-inf')

        for i, alt in enumerate(env.current_alts):
            alt_cpu = sum(nx.get_node_attributes(alt, 'cpu').values())
            alt_bw = sum(nx.get_edge_attributes(alt, 'bw').values())

            # Score = Negative Weighted Demand.
            # We want to MINIMIZE demand on the stressed resource.
            score = - (cpu_util * alt_cpu + bw_util * alt_bw)

            if score > best_score:
                best_score = score
                best_idx = i

        return best_idx

# ==========================================
# 5. FEATURE EXTRACTOR & UTILS
# ==========================================
class VNEAPFeatureExtractor(BaseFeaturesExtractor):
    def __init__(self, observation_space, features_dim=64):
        super().__init__(observation_space, features_dim)
        self.sub_encoder = nn.Sequential(nn.Linear(SUBSTRATE_NODES, 32), nn.ReLU())
        self.req_encoder = nn.Sequential(nn.Linear(NUM_ALTERNATIVES * MAX_VNR_NODES, 32), nn.ReLU())
        self.final_layer = nn.Linear(64, features_dim)

    def forward(self, observations):
        sub_emb = self.sub_encoder(observations['substrate_cpu'])
        req_emb = self.req_encoder(observations['request_state'].flatten(start_dim=1))
        return self.final_layer(torch.cat([sub_emb, req_emb], dim=1))

def run_evaluation(env, agent, target_requests=200):
    """
    Runs until exactly 'target_requests' have been processed (Accepted or Failed).
    Ensures fair quantitative comparison between agents with different speeds.
    """
    # 1. Seed for fair start
    obs, _ = env.reset(seed=42)

    total_reward = 0
    accepted_requests = 0
    processed_requests = 0

    cpu_util_history = []
    bw_util_history = []

    # Safety break to prevent infinite loops if agent gets stuck
    max_steps = target_requests * 15
    steps = 0

    while processed_requests < target_requests and steps < max_steps:
        steps += 1

        # --- Predict ---
        if isinstance(agent, MaskablePPO):
             action, _ = agent.predict(obs, action_masks=env.action_masks(), deterministic=True)
        else:
             if not env.unwrapped.mapping_phase:
                 action = agent.select_alternative(env.unwrapped)
             else:
                 action = agent.map_node(env.unwrapped)

        # --- Step ---
        obs, reward, done, _, info = env.step(action)
        total_reward += reward

        # --- Track Request Completion ---
        msg = info.get('msg', '')
        if msg in ["Fully Embedded", "Mapping Failed (CPU)", "Mapping Failed (BW)"]:
            processed_requests += 1
            if msg == "Fully Embedded":
                accepted_requests += 1

        # --- Record Stats ---
        u_cpu, u_bw = env.unwrapped.get_utilization()
        cpu_util_history.append(u_cpu)
        bw_util_history.append(u_bw)

    return accepted_requests, processed_requests, cpu_util_history, bw_util_history

# ==========================================
# 6. MAIN
# ==========================================
def main():
    log_dir = "./tmp/"
    os.makedirs(log_dir, exist_ok=True)
    # Fix: safely bypass Monitor for action_masks
    env = ActionMasker(Monitor(VNEAPEnv(), log_dir), lambda env: env.unwrapped.action_masks())

    # 1. Train
    print(f"Training RL Agent for {TRAINING_STEPS} steps...")
    model = MaskablePPO("MultiInputPolicy", env, policy_kwargs=dict(features_extractor_class=VNEAPFeatureExtractor), verbose=0)
    model.learn(total_timesteps=TRAINING_STEPS)
    print("Training Complete.")

    # 2. Compare & Collect Data
    print(f"\nEvaluating Agents (Target Requests={TARGET_REQS})...")
    results = {}

    # RL
    rl_acc, rl_tot, rl_cpu, rl_bw = run_evaluation(env, model, target_requests=TARGET_REQS)
    results['RL'] = {'acc': rl_acc, 'tot': rl_tot, 'cpu': rl_cpu, 'bw': rl_bw}

    # Greedy
    greedy = GreedyAgent("Greedy")
    gr_acc, gr_tot, gr_cpu, gr_bw = run_evaluation(env, greedy, target_requests=TARGET_REQS)
    results['Greedy'] = {'acc': gr_acc, 'tot': gr_tot, 'cpu': gr_cpu, 'bw': gr_bw}

    # Tanto
    tanto = TantoProxyAgent("Tanto")
    ta_acc, ta_tot, ta_cpu, ta_bw = run_evaluation(env, tanto, target_requests=TARGET_REQS)
    results['Tanto'] = {'acc': ta_acc, 'tot': ta_tot, 'cpu': ta_cpu, 'bw': ta_bw}

    # 3. Plotting
    print("\nGenerating Plots...")
    names = list(results.keys())

    # Plot A: Acceptance Count
    accs = [results[n]['acc'] for n in names]
    plt.figure(figsize=(8, 4))
    plt.bar(names, accs, color=['blue', 'orange', 'green'])
    plt.title(f"Requests Accepted (Target Attempts={TARGET_REQS})")
    plt.ylabel("Count")
    plt.ylim(0, TARGET_REQS)
    plt.show()

    # Plot B: Rejection Rate
    rej_rates = []
    for n in names:
        tot = results[n]['tot']
        acc = results[n]['acc']
        rate = ((tot - acc) / tot * 100) if tot > 0 else 0
        rej_rates.append(rate)

    plt.figure(figsize=(8, 4))
    plt.bar(names, rej_rates, color=['red', 'red', 'red'], alpha=0.6)
    plt.title(f"Rejection Rate %")
    plt.ylabel("Rejection %")
    plt.ylim(0, 100)
    plt.show()

    # Plot C: Utilization Comparison
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8))

    # CPU
    for name in names:
        ax1.plot(results[name]['cpu'], label=name, alpha=0.8)
    ax1.set_title("Substrate CPU Utilization Over Time")
    ax1.set_ylabel("% Used")
    ax1.legend()

    # BW
    for name in names:
        ax2.plot(results[name]['bw'], label=name, alpha=0.8)
    ax2.set_title("Substrate Link Bandwidth Utilization Over Time")
    ax2.set_xlabel("Simulation Steps")
    ax2.set_ylabel("% Used")
    ax2.legend()

    plt.tight_layout()
    plt.show()

    # Plot D: Training Curve (Smoothed)
    try:
        x, y = ts2xy(load_results(log_dir), 'timesteps')
        if len(x) > 0:
            window = 50
            if len(y) >= window:
                y_smooth = np.convolve(y, np.ones(window)/window, mode='valid')
                x_smooth = x[len(x)-len(y_smooth):]
            else:
                x_smooth, y_smooth = x, y

            plt.figure(figsize=(8, 4))
            plt.plot(x_smooth, y_smooth, color='purple')
            plt.title("RL Training Reward (Smoothed)")
            plt.xlabel("Timesteps")
            plt.ylabel("Episode Reward")
            plt.show()
    except Exception as e:
        print(f"Could not plot training curve: {e}")

if __name__ == "__main__":
    main()

"""### **How to Run This Example**

1.  **Dependencies:** Ensure you have `gymnasium`, `stable-baselines3`, `sb3-contrib`, and `networkx` installed.
2.  **Execution:** Save the code above as `vneap_orchestrator.py` and run it:
    ```bash
    python vneap_orchestrator.py
  ```
"""